# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'FinanceApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FinanceApp

  pod 'FacebookCore', '= 0.9.0'
  pod 'FacebookLogin', '= 0.9.0'
  pod 'FacebookShare', '= 0.9.0'

  pod 'Firebase/Core', '= 7.6.0'
  pod 'Firebase/Auth', '= 7.6.0'
  pod 'Firebase/Database', '= 7.6.0'
  pod 'Firebase/Storage', '= 7.6.0'
  pod 'Firebase/Firestore', '= 7.6.0'

  pod 'Alamofire', '= 5.4.1'
  pod 'Kingfisher', '= 6.1.0'

  pod 'Charts', '= 3.6.0'
  pod 'ChameleonFramework', '= 2.1.0'
  pod 'Eureka', '= 5.3.2'

end
